// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHello() {
  return window['go']['exposed']['HelloWails']['GetHello']();
}

export function SetCtx(arg1) {
  return window['go']['exposed']['HelloWails']['SetCtx'](arg1);
}
