// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {exposed} from '../models';

export function GetHello():Promise<string>;

export function SetCtx(arg1:context.Context):Promise<exposed.HelloWails>;
