// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ctx() {
  return window['go']['code']['App']['Ctx']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['code']['App']['OnSecondInstanceLaunch'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['code']['App']['SetCtx'](arg1);
}

export function Startup(arg1) {
  return window['go']['code']['App']['Startup'](arg1);
}

export function System() {
  return window['go']['code']['App']['System']();
}
