// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {options} from '../models';
import {code} from '../models';
import {configModel} from '../models';

export function Ctx():Promise<context.Context>;

export function InitLoadData(arg1:string):Promise<void>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<code.App>;

export function Startup(arg1:context.Context):Promise<void>;

export function System():Promise<configModel.System>;
