// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dataPanel/common/appConfig": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用设置"
                ],
                "summary": "获取应用配置信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置项key值binding:\"required\"",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "最新的配置值",
                        "name": "value",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "接口返回信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dataPanel/common/loadData": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用设置"
                ],
                "summary": "加载配置文件及股票基础数据",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoadDataParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "接口返回信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dataPanel/common/updateAppConfig": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用设置"
                ],
                "summary": "更新应用配置信息",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.ConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "接口返回信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.ConfigRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "配置项key值binding:\"required\"",
                    "type": "string"
                },
                "value": {
                    "description": "最新的配置值",
                    "type": "string"
                }
            }
        },
        "request.LoadDataParams": {
            "type": "object",
            "properties": {
                "dataSavePath": {
                    "type": "string"
                },
                "loadDataChecked": {
                    "description": "c:配置文件 a:A股 h:港股 m：美股",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "loadDataType": {
                    "description": "customize：历史数据导入   default：默认加载配置文件和加载数据",
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
